- name: Checkout
  uses: actions/checkout@v2.3.5
- name: Cache
  uses: actions/cache@v2.1.6
- name: Unity - Test runner
  uses: game-ci/unity-test-runner@v2.0-alpha-6
- name: Unity - Builder
  uses: game-ci/unity-builder@v2.0-alpha-13
